# Generated by Django 4.1.7 on 2023-05-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
