# Generated by Django 4.1.7 on 2023-05-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
